name: testing
concurrency: testing-v1

on:
  - push
  # workflow_dispatch:
  #   inputs:
  #     target:
  #       type: choice
  #       description: deploy target
  #       required: true
  #       default: staging
  #       options:
  #         - staging
  #         - production

# defaults:
#   run:
#     working-directory: ./foo

env:
  TZ: Asia/Tokyo

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      yay: ${{ steps.foo.outputs.test }}
    steps:
      - id: foo
        run: |
          echo "test=aaaa" >> "$GITHUB_OUTPUT"
      - run: echo ${{ steps.foo.outputs.test }}

      # - uses: actions/checkout@v4
      # - uses: docker/setup-buildx-action@v3
      # - uses: docker/metadata-action@v5
