name: testing
concurrency: testing-v1

defaults:
  run:
    working-directory: ./foo

env:
  TZ: Asia/Tokyo

jobs:
  build:
    runs-on: buildjet-2vcpu-ubuntu-2204
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
