name: testing
concurrency: testing-v1

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: deploy target
        required: true
        default: staging
        options:
          - staging
          - production

defaults:
  run:
    working-directory: ./foo

env:
  TZ: Asia/Tokyo

jobs:
  build:
    runs-on: buildjet-2vcpu-ubuntu-2204
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
