name: testing
concurrency: testing-v1

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: deploy target
        required: true
        default: staging
        options:
          - staging
          - production

defaults:
  run:
    working-directory: ./foo

env:
  TZ: Asia/Tokyo

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
